pub mod api_bridge;
pub mod auth;
pub mod auth_env_telemetry;
pub mod copilot_auth;
pub mod provider_auth;
pub mod token_data;

mod copilot_storage;
mod device_code_auth;
mod pkce;
mod server;

pub use codex_client::BuildCustomCaTransportError as BuildLoginHttpClientError;
pub use codex_config::types::AuthCredentialsStoreMode;
pub use device_code_auth::DeviceCode;
pub use device_code_auth::complete_device_code_login;
pub use device_code_auth::request_device_code;
pub use device_code_auth::run_device_code_login;
pub use server::LoginServer;
pub use server::ServerOptions;
pub use server::ShutdownHandle;
pub use server::run_login_server;

pub use api_bridge::auth_provider_from_auth;
pub use auth::AuthConfig;
pub use auth::AuthDotJson;
pub use auth::AuthManager;
pub use auth::AuthManagerConfig;
pub use auth::CLIENT_ID;
pub use auth::CODEX_API_KEY_ENV_VAR;
pub use auth::CodexAuth;
pub use auth::ExternalAuth;
pub use auth::ExternalAuthChatgptMetadata;
pub use auth::ExternalAuthRefreshContext;
pub use auth::ExternalAuthRefreshReason;
pub use auth::ExternalAuthTokens;
pub use auth::GEMINI_API_KEY_ENV_VAR;
pub use auth::GEMINI_API_PROVIDER_ID;
pub use auth::GOOGLE_API_KEY_ENV_VAR;
pub use auth::OPENAI_API_KEY_ENV_VAR;
pub use auth::OPENAI_PROVIDER_ID;
pub use auth::REFRESH_TOKEN_URL_OVERRIDE_ENV_VAR;
pub use auth::RefreshTokenError;
pub use auth::UnauthorizedRecovery;
pub use auth::default_client;
pub use auth::enforce_login_restrictions;
pub use auth::load_auth_dot_json;
pub use auth::login_with_api_key;
pub use auth::login_with_api_key_for_provider;
pub use auth::logout;
pub use auth::read_gemini_api_key_candidates_from_env;
pub use auth::read_openai_api_key_from_env;
pub use auth::save_auth;
pub use auth_env_telemetry::AuthEnvTelemetry;
pub use auth_env_telemetry::collect_auth_env_telemetry;
pub use copilot_auth::GITHUB_COPILOT_CLIENT_ID;
pub use copilot_auth::GitHubCopilotSession;
pub use copilot_auth::complete_github_copilot_device_code_login;
pub use copilot_auth::load_github_copilot_session;
pub use copilot_auth::logout_github_copilot;
pub use copilot_auth::request_github_copilot_device_code;
pub use copilot_auth::run_github_copilot_device_code_login;
pub use copilot_storage::GitHubCopilotAuth;
pub use copilot_storage::load_github_copilot_auth;
pub use provider_auth::ResolvedProviderApiAccess;
pub use provider_auth::auth_manager_for_provider;
pub use provider_auth::required_auth_manager_for_provider;
pub use provider_auth::resolve_provider_api_access;
pub use token_data::TokenData;
